import Navbar from "@/components/Navbar";
import WeatherCard from "@/components/WeatherCard";
import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState([]);

  const url = `http://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&APPID=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    axios
      .get(url)
      .then((res) => {
        setWeather([...weather, res.data]);
      })
      .catch((error) => {
        console.error(error);
        alert("Enter a valid city!");
        return;
      });

    setCity(" ");
  };

  return (
    <div className=" relative">
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="relative">
        <div className="relative h-[100vh]">
          <Image
            src="/pexels-benjamin-suter-2700532.jpg"
            alt="bacground image"
            fill
            className="object-cover"
          />
        </div>

        <section className="absolute top-10 left-0 right-0 w-full">
          <div
            className=" mx-auto py-12
          max-w-md
          lg:max-w-2xl"
          >
            <form className=" flex flex-col space-y-3" onSubmit={fetchWeather}>
              <input
                type="text"
                className="py-3 px-3 rounded-full opacity-80 text-center"
                onChange={(e) => setCity(e.target.value)}
                value={city}
              />
              <button
                className="bg-blue-500 text-white py-3 rounded-full "
                onClick={fetchWeather}
              >
                Search City
              </button>
            </form>
          </div>

          <div className=" max-w-md lg:max-w-2xl mx-auto space-x-3 overflow-auto scrollbar-hide flex py-6 ">
            {weather?.map((item) => (
              <WeatherCard
                key={item.name}
                name={item.name}
                temp={item.main.temp}
                weather={item.weather[0].main}
                feelsTemp={item.main.feels_like}
                tempMax={item.main.temp_max}
                tempMin={item.main.temp_min}
              />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
